services:
  web:
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k uvicorn.workers.UvicornWorker app.main:app --timeout 120
    envVars:
      - key: DATABASE_URL
      - key: TELEGRAM_BOT_TOKEN
    ports:
      - port: 10000